def massiv():
    menuData = [
        {
            "name": "Салат Цезарь",
            "image": "caesar.jpg",
            "description": "Свежий салат с куриным филе, листьями салата айсберг и хрустящими крутонами.",
            "totalWeight": "350 г",
            "calories": "350 ккал",
            "mealTime": "День",
            "containsMeat": 1,
            "seafood": 0,
            "healthy": 0,
            "drink": 1,
            "difficulty": "Легкий"
        },
        {
            "name": "Паста Карбонара",
            "image": "carbonara.jpg",
            "description": "Итальянская паста с беконом, яйцами и сливками.",
            "totalWeight": "350 г",
            "calories": "500 ккал",
            "mealTime": "День",
            "containsMeat": 1,
            "seafood": 0,
            "healthy": 0,
            "drink": 0,
            "difficulty": "Средний"
        },
        {
            "name": "Суп-лапша",
            "image": "soup.jpg",
            "description": "Питательный суп с говядиной, лапшой и свежими овощами.",
            "totalWeight": "450 г",
            "calories": "300 ккал",
            "mealTime": "День",
            "containsMeat": 1,
            "seafood": 0,
            "healthy": 0,
            "drink": 0,
            "difficulty": "Средний"
        },
        {
            "name": "Омлет",
            "image": "omelette.jpg",
            "description": "Нежный омлет с помидорами и сыром.",
            "totalWeight": "250 г",
            "calories": "250 ккал",
            "mealTime": "Утро",
            "containsMeat": 0,
            "seafood": 0,
            "healthy": 0,
            "drink": 0,
            "difficulty": "Легкий"
        },
        {
            "name": "Рис с овощами",
            "image": "rice_vegetables.jpg",
            "description": "Паровой рис с морковью, горошком и луком.",
            "totalWeight": "450 г",
            "calories": "400 ккал",
            "mealTime": "День",
            "containsMeat": 0,
            "seafood": 0,
            "healthy": 0,
            "drink": 0,
            "difficulty": "Легкий"
        },
        {
            "name": "Куриные крылышки",
            "image": "chicken_wings.jpg",
            "description": "Жареные куриные крылышки с соусом барбекю.",
            "totalWeight": "300 г",
            "calories": "450 ккал",
            "mealTime": "Вечер",
            "containsMeat": 1,
            "seafood": 0,
            "healthy": 0,
            "drink": 0,
            "difficulty": "Средний"
        },
        {
            "name": "Гречневая каша",
            "image": "buckwheat_porridge.jpg",
            "description": "Ароматная гречневая каша с маслом.",
            "totalWeight": "465 г",
            "calories": "350 ккал",
            "mealTime": "Утро",
            "containsMeat": 1,
            "seafood": 1,
            "healthy": 1,
            "drink": 1,
            "difficulty": "Легкий"
        },
        {
            "name": "Суп-харчо",
            "image": "harchosoup.jpg",
            "description": "Пикантный суп с говядиной, рисом и специями.",
            "totalWeight": "400 г",
            "calories": "280 ккал",
            "mealTime": "День",
            "containsMeat": 1,
            "seafood": 0,
            "healthy": 0,
            "drink": 0,
            "difficulty": "Средний"
        },
        {
            "name": "Пицца",
            "image": "pizza.jpg",
            "description": "Аппетитная пицца с ветчиной, сыром и соусом.",
            "totalWeight": "600 г",
            "calories": "600 ккал",
            "mealTime": "Вечер",
            "containsMeat": 1,
            "seafood": 0,
            "healthy": 0,
            "drink": 1,
            "difficulty": "Сложный"
        },
        {
            "name": "Фруктовый салат",
            "image": "fruitsalad.jpg",
            "description": "Свежий салат с яблоками, бананами, апельсинами и грушами.",
            "totalWeight": "450 г",
            "calories": "200 ккал",
            "mealTime": ["Утро", "Вечер"],
            "containsMeat": 0,
            "seafood": 0,
            "healthy": 1,
            "drink": 0,
            "difficulty": "Легкий"
        }
    ]
    return menuData